version: "v1"
project: "letschat"
services:
  frontend:
    node:
      image: "mikemichel/letschat"
      instances: 1
      mem: 1024
      domain: chat.sloppy.zone
      port: 8080
      env:
        - LCB_DATABASE_URI: "mongodb://mongodb.backend.letschat/letschat"
      dependencies:
        - "../backend/mongodb"
  backend:
    mongodb:
      image: "mongo"
      cmd: "mongod --smallfiles"
      instances: 1
      mem: 512
      volumes:
        - path: "/data/db"
        - path: "/data/configdb"
